-- stock info insert
insert into stock (created_at, updated_at, code, name) values (now(), now(),'005930','삼성전자');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'373220','LG에너지솔루션');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'000660','SK하이닉스');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'207940','삼성바이오로직스');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'005935','삼성전자우');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'051910','LG화학');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'006400','삼성SDI');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'035420','NAVER');
insert into stock (created_at, updated_at, code, name) values (now(), now(),'005380','현대차');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'035720','카카오');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000270','기아');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'068270','셀트리온');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'028260','삼성물산');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'005490','POSCO홀딩스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'105560','KB금융');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'012330','현대모비스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'096770','SK이노베이션');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'055550','신한지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'034730','SK');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'066570','LG전자');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'323410','카카오뱅크');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'015760','한국전력');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'034020','두산에너빌리티');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'003550','LG');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'259960','크래프톤');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'003670','포스코케미칼');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'032830','삼성생명');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'329180','현대중공업');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'011200','HMM');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'086790','하나금융지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'051900','LG생활건강');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'017670','SK텔레콤');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'033780','KT&G');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'010130','고려아연');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'010950','S-Oil');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'009150','삼성전기');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'018260','삼성에스디에스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'030200','KT');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'003490','대한항공');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000810','삼성화재');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'302440','SK바이오사이언스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'377300','카카오페이');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'009830','한화솔루션');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'316140','우리금융지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'036570','엔씨소프트');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'011070','LG이노텍');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'352820','하이브');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'090430','아모레퍼시픽');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'024110','기업은행');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'361610','SK아이이테크놀로지');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'086280','현대글로비스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'009540','한국조선해양');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'097950','CJ제일제당');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'011170','롯데케미칼');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'402340','SK스퀘어');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'326030','SK바이오팜');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'034220','LG디스플레이');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'251270','넷마블');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'383220','F&F');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'018880','한온시스템');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'035250','강원랜드');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'047810','한국항공우주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'069500','KODEX 200');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'032640','LG유플러스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'010140','삼성중공업');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'088980','맥쿼리인프라');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000720','현대건설');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'011790','SKC');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'161390','한국타이어앤테크놀로지');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'021240','코웨이');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'267250','HD현대');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000060','메리츠화재');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'004020','현대제철');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'005830','DB손해보험');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'028050','삼성엔지니어링');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'010620','현대미포조선');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'271560','오리온');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000100','유한양행');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'006800','미래에셋증권');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'180640','한진칼');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'078930','GS');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'004990','롯데지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'011780','금호석유');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'138040','메리츠금융지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'137310','에스디바이오센서');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'036460','한국가스공사');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'128940','한미약품');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'371460','TIGER 차이나전기차SOLACTIVE');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'029780','삼성카드');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'012450','한화에어로스페이스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'003410','쌍용C&E');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'071050','한국금융지주');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'020150','일진머티리얼즈');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'005940','NH투자증권');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'241560','두산밥캣');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'307950','현대오토에버');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'005387','현대차2우B');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'008560','메리츠증권');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'016360','삼성증권');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'047050','포스코인터내셔널');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'001450','현대해상');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'282330','BGF리테일');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'010060','OCI');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'028670','팬오션');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'002790','아모레G');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'139480','이마트');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'272210','한화시스템');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'000120','CJ대한통운');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'023530','롯데쇼핑');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'052690','한전기술');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'008930','한미사이언스');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'008770','호텔신라');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'064350','현대로템');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'112610','씨에스윈드');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'002380','KCC');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'006360','GS건설');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'007070','GS리테일');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'014680','한솔케미칼');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'030000','제일기획');
insert into stock (created_at, updated_at, code, name) values (now(),now(),'026960','동서');

-- stock_price insert
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005930',61500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'373220',452000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000660',95700);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'207940',875000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005935',56400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'051910',651000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'006400',624000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'035420',250000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005380',186000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'035720',79200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000270',76700);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'068270',202500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'028260',120500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005490',256000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'105560',50700);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'012330',211000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'096770',210500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'055550',35500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'034730',236000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'066570',102000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'323410',31200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'015760',21550);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'034020',21450);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'003550',84300);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'259960',258000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'003670',161500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'032830',62000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'329180',134500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'011200',23550);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'086790',38500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'051900',726000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'017670',51200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'033780',81200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'010130',589000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'010950',92300);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'009150',138000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'018260',133000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'030200',38000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'003490',26500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000810',198500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'302440',122000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'377300',68400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'009830',46600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'316140',12200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'036570',382500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'011070',347000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'352820',188000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'090430',128000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'024110',9690);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'361610',94700);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'086280',178500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'009540',92100);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'097950',419000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'011170',182000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'402340',43600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'326030',78000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'034220',16250);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'251270',67300);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'383220',149000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'018880',10600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'035250',26400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'047810',56100);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'069500',32915);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'032640',12350);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'010140',5990);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'088980',12850);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000720',46400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'011790',132500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'161390',38950);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'021240',65000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'267250',59400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000060',38150);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'004020',33250);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005830',62400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'028050',22400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'010620',108000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'271560',109000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000100',56800);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'006800',6730);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'180640',61800);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'078930',44200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'004990',38900);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'011780',131500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'138040',30050);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'137310',37350);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'036460',41700);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'128940',311500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'371460',16600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'029780',31550);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'012450',71400);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'003410',7030);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'071050',61200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'020150',72500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005940',10050);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'241560',33200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'307950',120500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'005387',89800);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'008560',4930);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'016360',35100);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'047050',25150);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'001450',34100);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'282330',174500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'010060',124000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'028670',5520);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'002790',35600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'139480',105000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'272210',15300);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'000120',126500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'023530',101500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'052690',74900);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'008930',41600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'008770',72200);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'064350',25750);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'112610',64900);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'002380',306000);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'006360',31500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'007070',25600);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'014680',230500);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'030000',22350);
insert into stock_price (created_at, updated_at, code, price) values (DATEADD('DAY', -1, now()),DATEADD('DAY', -1, now()),'026960',25650);